### ISSUE TITLE
Contribute your example to ipycanvas?

### ISSUE THREAD

**Issue by martinRenou** [johnowhitaker/days_of_code#1]
Hello there,

I've tried your `06_Interaction_with_ipycanvas.ipynb` Notebook and it looks amazing :) ! It would be awesome if you could contribute your Notebook to the [ipycanvas examples folder](https://github.com/martinRenou/ipycanvas/tree/master/examples), would you like to open a PR?

**Comment by johnowhitaker** [comment]
Hi there,
This slipped past me, so I have only just seen it now. I'd be happy to contribute an example - I will make a standalone notebook with this basic idea polished and documented and try to submit it tomorrow :)

**Comment by martinRenou** [comment]
That would be super cool :) Thanks!

**Comment by johnowhitaker** [comment]
Pull request to add it to the examples: https://github.com/martinRenou/ipycanvas/pull/190
Closing this issue - we can continue discussion in the pull request.
